"""V2 content for services 341-345 (not yet live). Written with the
highlights-chicago-service-page-v2 skill from the Content Plan, the permit
workbook and the related live pages (322, 327, 330, 333, 307).

Every page dict maps 1:1 to a 01 Pages row; ITEMS maps to 02 Items rows.
Reviews are looked up by ID from the Content Plan by add_batch.py.
"""

IMG = "/services/images/services/"
LIVE = "https://www.highlightschicago.com/services/"

PERMIT_NOTE = "Permit values are the reported construction value of the whole project, not a contractor quote."
CAPTION = "Reported construction value on Chicago electrical permits, 24 months to Aug 2026. Source: City of Chicago permit data."
PRICE_COLS = "Job || Reported median, or what drives the price || Permit needed?"

PAGES = []
ITEMS = {}


def page(**row):
    PAGES.append(row)


def items(sid, block, *rows):
    ITEMS.setdefault(sid, []).extend((block, list(r)) for r in rows)


# ---------------------------------------------------------------------------
# 341 Solar inverter installation
# ---------------------------------------------------------------------------
S = "341"
page(
    service_id=S, slug="solar-inverter-installation", name="Solar Inverter Installation & Solar Electrical Hookup",
    parent_name="Energy Efficiency & Solar", area_slug="chicago",
    meta_title="Solar Inverter Installation & Replacement in Chicago",
    meta_description="The inverter is the part of a solar system that fails first and the part that ties it to your panel and ComEd. Registered Chicago electricians. Call (773) 262-3333.",
    kw_primary="solar inverter installation || solar panel electrician", kw_volume="700",
    kw_secondary="solar pv installation || solar electrical hookup",
    h1_prefix="Solar Inverter Installation and Solar Electrical Hookup",
    hero_lede="The panels on the roof rarely fail. The inverter, the wiring down to your electrical panel and the connection to ComEd are where solar systems stop producing, and they are electrical work. Solar is the second-highest-volume electrical permit category in Chicago, with 4,033 permits in 24 months.",
    cta_secondary="Book an Inverter Check",
    issue_question="What do you need?",
    issue_options="Replace a failed inverter || Inverter showing an error || Electrical hookup for new panels || Add a battery to my inverter || Commercial or multi-unit system || Not sure which",
    jobs_heading="Which inverter job is yours?",
    jobs_lede="Inverter work comes in four shapes. They start with different checks, so find yours first.",
    jobs_note="Not sure which one fits? Choose “Not sure which” in the form and tell us the inverter make and model if you have it.",
    equip_heading="Inverters & Solar Electrical Equipment We Work On",
    equip_lede="String, micro and hybrid inverters, plus the disconnects, breakers and service equipment every array depends on.",
    equip_footnote="Inverter faults, dead strings and monitoring dropouts on existing systems are a large share of this work.",
    equip_footnote_link_label="Symptoms and what we check", equip_footnote_link_anchor="diagnose",
    compare_heading="String inverter, microinverters or a hybrid inverter: what changes?",
    compare_intro="When an inverter is replaced, the type does not have to stay the same. Here is what actually differs.",
    compare_columns="String inverter || Microinverters || Hybrid (battery-ready) inverter",
    options_heading="Replacing a failed inverter: three routes",
    options_callout_lead="A failed inverter does not mean a new solar system.",
    options_callout_body="The panels usually outlast the inverter. What changes the price is whether the same model, or one that fits the same wiring, is still made.",
    options_note="Which route fits is decided after we read the error history and check the panels and wiring. [CONFIRM: whether Highlights handles manufacturer warranty claims for customers or supplies diagnosis evidence only]",
    assess_heading="What we check before quoting inverter work",
    assess_lede="Most of the price is decided by what is already on the wall and in the panel. This is what we look at, and why.",
    routes_heading="If your panel can't take the inverter output",
    routes_note="Which route fits is decided on site and written into the scope before work starts.",
    diagnose_heading="Solar not producing? Where the inverter fits in",
    diagnose_lede="The symptom tells us where to start looking, not what to replace.",
    diagnose_columns="What you're seeing || Common causes we check || Where we start",
    repair_title="Repair, replace or upgrade?",
    repair_body="If the inverter is still supported, we repair it or swap it like for like. If it is discontinued, the replacement may need different wiring or a different inverter type, which changes the scope and the price. Equipment under manufacturer warranty usually goes through the manufacturer's claim process.",
    orphan_title="Original installer closed?",
    orphan_body="We work on systems we did not install. Bring what you have: inverter make and model, a photo of the error screen, the monitoring login and any permit paperwork. Missing documents slow the diagnosis down but do not stop it.",
    brands_heading="Inverter & Solar Equipment Brands We Work With",
    brands_lede="Most of what we meet on Chicago rooftops comes from a short list of manufacturers.",
    brands="Enphase || SolarEdge || SMA || Fronius || Tesla || Generac PWRcell || Qcells || Square D || Siemens || Eaton",
    brands_note="We work on customer-specified and previously installed equipment, including systems we did not install.",
    why_heading="Why Highlights Chicago for Inverter Work?",
    why_lede="Inverter problems are electrical problems, and the fix often runs through your panel.",
    process_heading="From diagnosis to switch-on: who controls each step",
    process_lede="Inverter swaps are quick. The steps around them are what take time, and some belong to the City or ComEd.",
    areas_callout="For inverter work specifically: older Chicago panels often sit in basements far from the roof, brick walls lengthen conduit routes, and on two-flats we confirm which meter the system feeds before touching it.",
    feature_tag="Main category", feature_title="All Energy Efficiency & Solar Services",
    feature_desc="Every service we offer in the Energy Efficiency & Solar cluster across Chicago.",
    pricing_heading="What Inverter Work Costs",
    pricing_lede="Chicago publishes reported construction value on every permit. Inverter work sits inside the solar category, one of the most reliable medians in the dataset.",
    pricing_caption=CAPTION, pricing_columns=PRICE_COLS,
    pricing_note=PERMIT_NOTE + " Inverter replacement is not reported as its own permit category, so the solar figure covers whole systems.",
    drivers_heading="What moves the price of inverter work",
    incentives_note="Incentives can change the net cost of new solar equipment. [CONFIRM: current Illinois Shines, ComEd and federal incentive status before stating anything here]",
    incl_heading="What's included, what isn't, and what you get at the end",
    incl_lede="Inverter quotes differ most in what they leave out. Here is how ours is drawn.",
    in_scope_heading="In a typical inverter replacement",
    in_scope="Diagnosis of the existing system || Removal of the failed inverter || New inverter mounted and wired || Disconnects and labelling brought up to current requirements || Permit application and closeout where required || Monitoring reconnected on your own account",
    in_scope_note="[CONFIRM: each line above against Highlights' standard inverter scope]",
    separate_heading="Quoted separately, when needed",
    separate="Panel or service upgrade || Battery and backup subpanel || Roof or racking repairs || Replacing damaged panels or optimisers || ComEd meter work",
    separate_note="[CONFIRM: whether roof penetrations are done in-house or by a roofing partner]",
    handover_heading="What you should have at handover",
    handover="Permit closed and inspection passed, where a permit was needed || Monitoring app on your own account || Inverter make, model and serial number || Manufacturer warranty registration || Written workmanship warranty",
    warranty_heading="Who warrants what",
    cta_heading="Inverter not working", cta_body="Free estimate, a written scope before we start, and a contractor registered to pull the permit if the work needs one.",
    ready_heading="Have these ready when you call",
    ready_items="Inverter make and model (on the label) || A photo of any error code or the monitoring screen || A photo of your electrical panel, door open || Roughly when the system was installed, and by whom || For a condo or two-flat: who handles approvals",
    guide_title="Solar Inverter Installation — Detail", guide_heading="Solar inverters in Chicago: the practical detail",
    guide_intro="Solar permits are the second-highest-volume electrical category in Chicago, with 4,033 in 24 months. As those systems age, the inverter is the component most likely to need attention first.",
)
items(S, "form_field",
      ["existingSystem", "Do you already have solar?", "Yes, and the original installer is still around || Yes, but the original installer has closed || Yes, not sure who installed it || No, this would be a new system"],
      ["symptom", "What is the system doing?", "Not applicable || Producing nothing || Producing less than before || Inverter showing an error || Monitoring app offline || Breaker keeps tripping"])
items(S, "job_path",
      ["Replace a failed inverter", "Your system stopped producing and the inverter shows an error or nothing at all.", "Whether the same or a compatible model is still made, and the condition of the wiring.", "Diagnostic visit.", "Symptoms and what we check", "diagnose"],
      ["Electrical hookup for new panels", "You have panels or a quote, and need the inverter, disconnects and panel connection done.", "Panel busbar and main breaker rating, conduit route and meter arrangement.", "Panel and service check.", "What we check", "site-assessment"],
      ["Add a battery to your inverter", "You have solar and want backup during outages.", "Whether your inverter can pair with a battery, and which circuits must keep running.", "Tell us your inverter make and model.", "Replacement routes", "equipment-options"],
      ["Commercial or multi-unit", "You own or manage a commercial, mixed-use or multi-unit building with solar.", "Service size, metering and owner or association approvals.", "Site walk, with drawings if you have them.", "The full sequence", "process"])
items(S, "equipment",
      ["String inverters", "One central unit on the wall"], ["Microinverters", "One per panel, under the array"],
      ["Hybrid inverters", "Battery-ready, backup capable"], ["DC & AC disconnects", "Required shutoffs, labelled"],
      ["Rapid shutdown devices", "Rooftop safety shutoff"], ["Panel & service connections", "Where the system meets your panel"])
items(S, "compare_row",
      ["Where the power is converted", "One unit, usually near the panel", "Under every panel", "One unit that also manages a battery"],
      ["If one part fails", "The whole system or string stops", "Usually only that panel stops", "The whole system stops, with backup depending on setup"],
      ["Monitoring detail", "Whole system or per string", "Per panel", "Whole system, plus battery status"],
      ["Replacing it later", "One unit to swap", "Individual units, on the roof", "One unit; the battery must stay compatible"],
      ["Adding a battery", "Depends on the model, so ask", "Usually an AC-coupled battery", "Designed for it"])
items(S, "option",
      ["Like-for-like swap", "Same model or a direct replacement that fits the existing wiring and mounting. Usually the quickest route."],
      ["Compatible replacement", "A different model that works with your panels and string layout. May need new wiring or disconnects."],
      ["Upgrade the type", "Switching to microinverters or a hybrid inverter, often when shading is a problem or a battery is planned."])
items(S, "assess_check",
      ["Inverter make, model and age", "Decides whether a like-for-like replacement exists or the type has to change."],
      ["Error history", "The code and the monitoring history narrow down whether the fault is the inverter or something upstream."],
      ["Panel and string condition", "A failed panel or connector can look like an inverter fault."],
      ["Panel busbar and main breaker", "Code limits how much solar can feed back into a panel, based on these ratings."],
      ["Electric service size", "A 100A service limits how much solar can connect."],
      ["Disconnects and labelling", "Older systems often predate current shutoff and labelling requirements."],
      ["Rapid shutdown", "Rooftop systems need a way to de-energise the array quickly; older ones may not have it."],
      ["Conduit route", "Distance from roof to panel, floors and brick walls change the labour."],
      ["Monitoring access", "Who owns the monitoring account decides how quickly we can see the history."])
items(S, "route",
      ["The panel has capacity", "The inverter connects through a breaker in your existing panel. No panel work."],
      ["The panel is short, the service is fine", "A connection on the supply side of the main breaker, or a panel with a larger busbar."],
      ["The service is too small", "A service upgrade, for example 100A to 200A, then the inverter connects. ComEd schedules its part."])
items(S, "symptom",
      ["Nothing produced on a sunny day", "Tripped solar breaker or disconnect, inverter shut down, a grid fault that hasn't cleared", "Breakers, disconnects and inverter status"],
      ["Inverter showing an error", "Ground or isolation fault, grid voltage out of range, an internal inverter failure", "The error code against the manufacturer's documentation"],
      ["Less production than last year", "A failed panel or optimiser, a dead string, shading from tree growth", "Monitoring history, by panel or string"],
      ["Inverter clicks on and off", "Grid voltage at the edge of its range, a loose connection, overheating", "Voltage at the inverter and terminations"],
      ["Monitoring app offline", "A changed Wi-Fi network, a failed gateway; the system may be producing fine", "Gateway and network"],
      ["Solar breaker keeps tripping", "A loose termination, an undersized breaker, an inverter fault", "Terminations, breaker sizing and the inverter"])
items(S, "why",
      ["Solar is 20% of Chicago's electrical permits", "4,033 permits in 24 months, median reported value $18,992. As those systems age, inverters are what need replacing.", "", ""],
      ["The panel is usually the constraint", "Pre-war buildings often need panel or service work before solar connects, and we do both under one licence.", "What we check", "site-assessment"],
      ["We work on systems we did not install", "Many installers will not touch another company's array. Inverter replacements are a common call when the original installer has gone.", "", ""],
      ["Permit pulled and closed in-house", "ECC96456 and ECC94521. Our record shows 527 permits through the Express Permit Program.", "", ""],
      ["ComEd coordination is part of the job", "Interconnection paperwork and utility scheduling are handled, not left to you.", "Every step, and who controls it", "process"],
      ["Salaried crews, scope pricing", "No commissioned salesperson. The fix is sized to the fault, not to a new system.", "", ""])
items(S, "process_step",
      ["Diagnosis", "We read the error history, test the inverter, panels and wiring, and tell you what failed. [CONFIRM: typical diagnostic visit length]", "highlights"],
      ["Written scope", "Repair, like-for-like swap or upgrade, with any panel work and the price, in writing.", "highlights"],
      ["Permit, where required", "We apply; the City reviews and issues. Our own permits have averaged 29.7 days to process across all work types. [CONFIRM: which inverter replacements need a new permit]", "city"],
      ["Utility paperwork, where required", "A changed system size or inverter type can need ComEd's approval before switch-on.", "comed"],
      ["Installation", "Inverter mounted, wired, disconnects and labels updated.", "highlights"],
      ["Inspection", "The inspector checks the work; we attend and correct anything flagged.", "city"],
      ["Switch-on and handover", "We switch on, reconnect monitoring on your own account and hand over the documents.", "highlights"])
items(S, "other_service",
      ["Solar Panel Installation & Service", "Solar is the second-highest-volume permitted electrical category in Chicago.", LIVE + "solar-panel-installation"],
      ["Solar Battery Installation", "Battery backup sized to your panel capacity and the circuits that matter.", LIVE + "solar-battery-installation"],
      ["Electrical Panel Upgrade", "The panel is usually the constraint before solar connects.", LIVE + "electrical-panel-upgrade"],
      ["Home & Commercial Energy Audit", "An energy audit tells you which upgrades are actually worth doing.", LIVE + "home-energy-audit"])
items(S, "price_row",
      ["Solar / photovoltaic (4,033 permits)", "$18,992 median reported", "Yes"],
      ["Electrical panel work (5,219 permits)", "$15,906 median reported", "Yes"],
      ["200A service upgrade (2,863 permits)", "$4,700 median reported", "Yes"],
      ["Inverter replacement, like for like", "Inverter price and whether the model is still made", "Sometimes"],
      ["Inverter type change", "New wiring, disconnects and mounting", "Usually"],
      ["Inverter diagnosis", "Time to find the fault and access to monitoring", "No"])
items(S, "cost_driver",
      ["Inverter type and size", "Microinverters mean units under every panel; string and hybrid units differ in price", "Assessment"],
      ["Part availability", "A discontinued model can force a type change and new wiring", "Diagnosis"],
      ["Panel capacity", "A short busbar or small service means panel or service work first", "Assessment"],
      ["Conduit route", "Distance, floors and brick walls change the labour", "Assessment"],
      ["Roof access", "Microinverter and optimiser work happens on the roof", "Assessment"],
      ["Code updates", "Older systems may need disconnects, labels or rapid shutdown added", "Assessment"],
      ["Utility paperwork", "A changed system can need ComEd approval", "Written scope"],
      ["Extra visits", "Waiting on parts, ComEd or re-inspection", "During the job, and stated in the scope where known"])
items(S, "warranty",
      ["Workmanship", "Highlights Chicago. [CONFIRM: term and what it covers]"],
      ["Inverter", "The manufacturer. Terms vary by brand, and some need registering after install."],
      ["Panels", "The manufacturer, with a product warranty and a separate output warranty."])
items(S, "faq",
      ["How long does a solar inverter last?", "Inverters usually need attention long before the panels do. The make, model and operating conditions decide the actual life, so we read the error history before recommending a replacement."],
      ["Can you replace an inverter on a system you did not install?", "Yes. Bring the inverter make and model, a photo of the error and the monitoring login if you have it."],
      ["Do I need a permit to replace a solar inverter?", "It depends on the scope. A change of inverter type or system size usually needs one. [CONFIRM: whether a like-for-like inverter swap needs a permit in Chicago]"],
      ["Can I add a battery to my existing inverter?", "Sometimes. It depends on the inverter model. Hybrid inverters are built for it; others need an AC-coupled battery. We check before recommending equipment."],
      ["Why does my inverter keep shutting off?", "Common causes are grid voltage at the edge of its range, a loose connection or overheating. The error log usually tells us which."],
      ["Will my inverter work during a power outage?", "Not on its own. A grid-tied inverter shuts off when the grid goes down so it can't feed lines crews are working on. Backup needs a battery and a backup-capable setup."],
      ["My installer went out of business. Who handles the warranty?", "Equipment warranties usually sit with the manufacturer, so they can still apply. We can diagnose the fault and give you what the manufacturer asks for."])
items(S, "guide_section",
      ["Why the inverter fails first", "Panels are passive and sealed. The inverter converts power all day, runs hot and is full of electronics, so it is usually the first component to need attention.\n\nA dead inverter usually means a working array that cannot deliver power, not a failed system."],
      ["How panel capacity limits solar", "An inverter feeds power back through your panel. Code caps how much it can feed, based on the panel's busbar rating and main breaker. A full or small panel may not have room, which is why a panel or service upgrade sometimes comes first."],
      ["Changing inverter type", "If your model is discontinued, the replacement may be a different type. Microinverters add equipment under every panel; a hybrid inverter prepares the system for a battery. Each changes the wiring, the price and sometimes the permit route."],
      ["Older systems and current requirements", "Systems installed years ago may not have the disconnects, labels or rapid shutdown that current rules expect. When we replace the inverter we tell you what the inspector will look for, before the work starts."])

# ---------------------------------------------------------------------------
# 342 AV installation & whole-home audio
# ---------------------------------------------------------------------------
S = "342"
page(
    service_id=S, slug="av-installation-services", name="AV Installation & Whole-Home Audio Wiring",
    parent_name="Low Voltage, Data & AV", area_slug="chicago",
    meta_title="AV Installation & Whole-Home Audio Wiring in Chicago",
    meta_description="TV mounts, in-wall speakers and whole-home audio need power, cable routes and clean walls before any equipment goes up. Chicago electricians. Call (773) 262-3333.",
    kw_primary="av installation services || whole home audio installation", kw_volume="650",
    kw_secondary="audio video wiring installation || av wiring contractor",
    h1_prefix="AV Installation and Whole-Home Audio Wiring",
    hero_lede="Speakers, screens and streamers are the easy part. The hard part is behind the wall: getting power and cable to the right places through plaster and brick, without a mess and without interference. That is wiring work, and it is what we do.",
    cta_secondary="Book a Wiring Walkthrough",
    issue_question="What do you need?",
    issue_options="Whole-home audio || TV wall mount with hidden wiring || Home theater or media room || Pre-wire during a renovation || Commercial AV wiring || Not sure which",
    jobs_heading="Which AV job is yours?",
    jobs_lede="AV wiring is four different jobs. They start in different places, so find yours first.",
    jobs_note="Not sure which one fits? Choose “Not sure which” in the form and tell us the rooms involved.",
    equip_heading="AV & Audio Wiring We Install",
    equip_lede="The cable, power and control layer behind speakers, screens and streaming systems.",
    equip_footnote="We wire and power; your AV integrator or you configure the equipment. We coordinate rather than work at cross purposes.",
    compare_heading="Wired, wireless or a hybrid audio system: what changes?",
    compare_intro="The choice decides how much wiring goes into the walls. Here is what actually differs.",
    compare_columns="Wired (central amplifier) || Wireless speakers || Hybrid (wired speakers, streaming amps)",
    options_heading="Before walls close, or after?",
    options_callout_lead="The cheapest time to run cable is when the walls are open.",
    options_callout_body="Retrofitting into finished plaster or brick is possible, but every run takes longer and some locations are not practical.",
    options_note="If a renovation is planned, a pre-wire now costs far less than fishing cable later.",
    assess_heading="What the walkthrough checks",
    assess_lede="Most of what decides the price is found in the walls and the basement. This is what we look at, and why.",
    brands_heading="Cabling & Control Brands We Install",
    brands_lede="We install the cable, connectors and controls that AV systems run on.",
    brands="Control4 || Lutron || Leviton || Legrand || Panduit || Belden || CommScope || Siemon || Ubiquiti || Ortronics",
    brands_note="Speaker and electronics brands are your choice or your integrator's; we wire to suit them.",
    why_heading="Why Highlights Chicago for AV Wiring?",
    why_lede="Most AV problems are cable and power problems.",
    process_heading="From walkthrough to working system",
    process_lede="The sequence matters most when other trades are involved.",
    areas_callout="For AV wiring specifically: plaster-and-lath walls and brick party walls change how cable is routed, and in condo buildings the association may need to approve work in common walls or ceilings.",
    feature_tag="Main category", feature_title="All Low Voltage, Data & AV Services",
    feature_desc="Every service we offer in the Low Voltage, Data & AV cluster across Chicago.",
    pricing_heading="What AV Wiring Costs",
    pricing_lede="Chicago's low voltage and data permits report a median, but it is driven by large commercial jobs. For homes, the scope drivers below matter more.",
    pricing_caption=CAPTION, pricing_columns=PRICE_COLS,
    pricing_note=PERMIT_NOTE + " The low voltage figure covers the whole low voltage and data category, which includes large commercial cabling.",
    drivers_heading="What moves the price of AV wiring",
    incl_heading="What's included, what isn't, and what you get at the end",
    incl_lede="AV quotes differ most in where the wiring stops and the equipment starts.",
    in_scope_heading="In a typical AV wiring scope",
    in_scope="Walkthrough and cable plan || Speaker and in-wall cable runs || Wall plates and connections || Power outlets behind screens and equipment || Patching and cleanup at our openings || Labelled cable at the equipment location",
    in_scope_note="[CONFIRM: each line above against Highlights' standard AV scope, including how much wall patching is included]",
    separate_heading="Quoted separately, when needed",
    separate="Speakers, screens and electronics || System programming and app setup || Painting after patching || New circuits from the panel || Network equipment",
    handover_heading="What you should have at handover",
    handover="Every cable labelled at both ends || A simple map of where cables run || Tested speaker and video connections || Clean wall openings, patched where agreed",
    cta_heading="Planning AV wiring", cta_body="Free estimate, a written scope before we start, and a registered electrical contractor if the job needs new power.",
    ready_heading="Have these ready when you call",
    ready_items="Which rooms you want covered || Where screens and speakers should go || Photos of the walls and ceiling || Any equipment you have already bought || For a condo: who handles approvals",
    guide_title="AV Installation & Whole-Home Audio — Detail", guide_heading="AV wiring in Chicago homes: the practical detail",
    guide_intro="AV systems keep changing; the cable in the wall stays for decades. Getting the wiring right is the part worth doing properly.",
)
items(S, "job_path",
      ["Whole-home audio", "You want music in several rooms, controlled from one app or keypad.", "Number of rooms, wired or wireless speakers, and where the equipment lives.", "Walkthrough.", "Wired or wireless", "equipment-choices"],
      ["TV with hidden wiring", "You want a wall-mounted screen with no visible cables.", "Wall type, what is inside the wall, and whether power is nearby.", "Photos of the wall.", "What we check", "site-assessment"],
      ["Home theater or media room", "You want a dedicated room with surround sound and a projector or large screen.", "Speaker layout, cable runs and dedicated power.", "Walkthrough with your plan.", "The full sequence", "process"],
      ["Pre-wire during a renovation", "Your walls are open, or will be soon.", "Timing with the other trades and where future equipment will go.", "Call before the drywall goes up.", "Before or after", "equipment-options"])
items(S, "equipment",
      ["In-wall & in-ceiling speakers", "Cable runs and backboxes"], ["Whole-home audio", "Multi-room cable to one hub"],
      ["TV & projector wiring", "Hidden HDMI and power"], ["Home theater", "Surround layouts and subwoofers"],
      ["Volume & control keypads", "Wall controls in each room"], ["Equipment power", "Outlets where gear actually sits"])
items(S, "compare_row",
      ["Cable in the walls", "Speaker cable to every room", "Power only, near each speaker", "Speaker cable to every room"],
      ["Sound reliability", "Not affected by Wi-Fi", "Depends on your network", "Not affected by Wi-Fi for the speakers"],
      ["Best fit", "Renovations and new builds", "Finished walls, renters, quick installs", "Most retrofits with open access"],
      ["Changing it later", "Swap the amplifier, keep the cable", "Swap the speakers", "Swap the amps, keep the cable"])
items(S, "option",
      ["Walls open", "Pre-wire every room you might want, even if equipment comes later. Cable is cheap compared with opening finished walls."],
      ["Finished walls", "We fish cable through existing cavities, attics and basements. Some routes need small openings that are patched."],
      ["Brick or concrete", "Surface raceway or a different route may be the honest answer; we say so before quoting."])
items(S, "assess_check",
      ["Wall construction", "Plaster and lath, drywall and brick each change how cable is fished."],
      ["Fire blocks and framing", "Older buildings often have blocking that stops a straight cable run."],
      ["Basement and attic access", "Open access above or below makes most runs simpler."],
      ["Power near the equipment", "Screens and amplifiers need outlets where they sit, not an extension cord."],
      ["Where the equipment lives", "One central location keeps cable runs short and tidy."],
      ["Interference", "Speaker and video cable run alongside power can pick up noise; we plan separation."],
      ["Building approvals", "In condos, work in common walls may need association sign-off."])
items(S, "why",
      ["We treat low voltage as real electrical work", "A poorly terminated speaker or video run causes the same intermittent faults as bad line-voltage wiring.", "", ""],
      ["Power and cable from one contractor", "When a screen needs a new outlet or a rack needs a circuit, it is the same crew.", "", ""],
      ["Chicago walls are routine for us", "Plaster, lath and brick are what we work in every week.", "What we check", "site-assessment"],
      ["We coordinate with your integrator", "We wire; your AV company configures. Clear handoff, no finger-pointing.", "", ""],
      ["Registered electrical contractor", "ECC96456 and ECC94521, which matters when AV work needs new circuits.", "", ""],
      ["Salaried crews, scope pricing", "A small wiring job is priced as a small job.", "", ""])
items(S, "process_step",
      ["Walkthrough", "We look at the rooms, walls and access, and agree where everything goes. [CONFIRM: typical walkthrough length]", "highlights"],
      ["Cable plan and written scope", "Every run, outlet and opening, with the price, in writing.", "highlights"],
      ["Equipment choice", "You or your integrator choose speakers, screens and electronics, so the wiring matches.", "customer"],
      ["Rough-in", "Cable runs, backboxes and any new outlets, before walls close where possible.", "highlights"],
      ["Trim and connections", "Plates, terminations and labelling.", "highlights"],
      ["Testing and handoff", "We test every run and hand over to you or your integrator for setup.", "highlights"])
items(S, "other_service",
      ["Structured & Network Cabling Installation", "Ethernet runs, patch panels and termination for networks that need to perform.", LIVE + "structured-cabling-installation"],
      ["Low Voltage Wiring Installation", "Doorbells, sensors, thermostats and control wiring.", LIVE + "low-voltage-wiring-installation"],
      ["CCTV & Security Camera Wiring", "Camera systems ride on the same low-voltage infrastructure as your network.", LIVE + "cctv-installation"],
      ["Electrical Outlet Installation", "New outlets where equipment actually sits.", LIVE + "electrical-outlet-installation"])
items(S, "price_row",
      ["Low voltage / data cabling (2,074 permits)", "$15,000 median reported, driven by commercial jobs", "Sometimes"],
      ["TV wall mount with hidden wiring", "Wall type and whether power is nearby", "Usually not"],
      ["Whole-home audio", "Number of rooms and cable route", "Usually not"],
      ["Home theater pre-wire", "Speaker count and access", "Usually not"],
      ["New outlet or circuit for equipment", "Distance to the panel and wall type", "Usually"])
items(S, "cost_driver",
      ["Number of rooms and runs", "Each run is labour from equipment location to the room", "Walkthrough"],
      ["Wall type", "Plaster and brick take longer than drywall", "Walkthrough"],
      ["Access", "Open basements and attics make runs simpler", "Walkthrough"],
      ["Walls open or closed", "Open walls are much faster", "Walkthrough"],
      ["New power", "Outlets or circuits for equipment add electrical work", "Written scope"],
      ["Patching", "How much finishing is included at openings", "Written scope"])
items(S, "faq",
      ["Do you install the speakers and TVs too?", "We run the cable and power and install backboxes and plates. Equipment choice and setup are usually yours or your integrator's. [CONFIRM: whether Highlights mounts TVs and speakers]"],
      ["Can you hide TV wires in a plaster or brick wall?", "Usually in plaster, with care. Brick and concrete walls often need a different route or a surface raceway, and we say so before quoting."],
      ["Wired or wireless speakers?", "Wired speakers are not affected by Wi-Fi and the cable lasts decades. Wireless speakers are quicker to install but still need power nearby."],
      ["Should I pre-wire during my renovation?", "Yes, if walls are open. Cable is cheap compared with opening finished walls later."],
      ["Does AV wiring need a permit?", "Low voltage cable often does not; new outlets and circuits for equipment usually do. We pull the permit when it applies."],
      ["Can you work with my AV company?", "Yes. We wire and power; they configure. We agree the plan with them first."])
items(S, "guide_section",
      ["Why the cable matters more than the equipment", "Amplifiers, streamers and screens get replaced every few years. The cable in your walls stays. Running good cable to the right places once means future upgrades are a swap, not a renovation."],
      ["Chicago walls and cable routes", "Plaster and lath walls hide blocking and old wiring. Brick party walls and concrete in high-rises rule out some routes. We plan runs through basements, attics and closets first, and only open walls where it is the honest answer."],
      ["Power where equipment sits", "Screens and amplifiers plugged into extension cords are a common cause of clutter and nuisance problems. An outlet behind the screen and a dedicated circuit for a large rack keep things tidy and safe."],
      ["Working with other trades", "In a renovation, the AV rough-in has to happen after framing and before drywall. Agreeing the sequence early avoids the most expensive mistake: finished walls with no cable."])

# ---------------------------------------------------------------------------
# 343 Well pump & electric water heater wiring
# ---------------------------------------------------------------------------
S = "343"
page(
    service_id=S, slug="well-pump-wiring", name="Well Pump & Electric Water Heater Wiring",
    parent_name="Appliance & Equipment Circuits", area_slug="chicago",
    meta_title="Electric Water Heater & Well Pump Wiring in Chicago",
    meta_description="Electric water heaters and well pumps need a correctly sized dedicated 240V circuit and a disconnect. Registered Chicago electricians. Call (773) 262-3333.",
    kw_primary="well pump wiring || electric water heater wiring", kw_volume="510",
    kw_secondary="water heater electrical hookup",
    h1_prefix="Well Pump and Electric Water Heater Wiring",
    hero_lede="A water heater or pump is plumbing on one side and a dedicated 240V circuit on the other. The electrical half is where the problems start: an undersized wire, a missing disconnect or a panel without room. That is the half we do.",
    cta_secondary="Book a Circuit Check",
    issue_question="What do you need?",
    issue_options="New electric water heater circuit || Switching from gas to electric || Tankless electric water heater || Well pump wiring || Water heater or pump has no power || Not sure which",
    jobs_heading="Which job is yours?",
    jobs_lede="Water heater and pump wiring is four different jobs. Find yours first.",
    jobs_note="Not sure which one fits? Choose “Not sure which” and send a photo of the unit's label.",
    equip_heading="Water Heater & Pump Circuits We Install",
    equip_lede="Dedicated 240V circuits, disconnects and controls for water heating and pumping equipment.",
    equip_footnote="We do the electrical side and coordinate with your plumber for the unit itself.",
    compare_heading="Tank, tankless or heat pump water heater: what changes electrically?",
    compare_intro="The type you choose decides the circuit you need. Here is what actually differs.",
    compare_columns="Electric tank || Electric tankless || Heat pump water heater",
    assess_heading="What we check before quoting",
    assess_lede="Most of the price is decided by your panel and the distance to it.",
    routes_heading="If your panel can't take the new load",
    routes_note="Which route fits is decided on site and written into the scope before work starts.",
    diagnose_heading="No hot water or no water pressure? What we check",
    diagnose_lede="The symptom tells us where to start. Many faults are electrical, not the unit.",
    diagnose_columns="What you're seeing || Common causes we check || Where we start",
    brands_heading="Water Heater & Electrical Brands We Work With",
    brands_lede="We wire to the manufacturer's requirements for whatever unit your plumber installs.",
    brands="Rheem || A. O. Smith || Square D || Siemens || Eaton || Leviton || Southwire || Cerrowire || Intermatic || Hubbell",
    why_heading="Why Highlights Chicago for Water Heater & Pump Wiring?",
    why_lede="A dedicated circuit done properly is the whole job.",
    process_heading="From check to hot water: who controls each step",
    process_lede="When a plumber is involved, the order matters.",
    areas_callout="For this work specifically: most Chicago homes are on city water, so in the city this is mostly water heater wiring. Well pumps come up outside the city. [CONFIRM: which areas Highlights serves for well pump work, given registrations are current only in Chicago, Evanston and Palatine]",
    feature_tag="Main category", feature_title="All Appliance & Equipment Circuits Services",
    feature_desc="Every service we offer in the Appliance & Equipment Circuits cluster across Chicago.",
    pricing_heading="What Water Heater & Pump Wiring Costs",
    pricing_lede="Chicago does not report water heater or pump circuits as their own permit category, so the scope drivers below matter most.",
    pricing_caption=CAPTION, pricing_columns=PRICE_COLS, pricing_note=PERMIT_NOTE,
    drivers_heading="What moves the price",
    incl_heading="What's included, what isn't, and what you get at the end",
    incl_lede="Quotes differ most in where the electrical work stops and the plumbing starts.",
    in_scope_heading="In a typical circuit scope",
    in_scope="Load and panel check || Dedicated circuit and breaker || Correctly sized wire || Disconnect at the unit || Connection to the unit || Permit and inspection where required",
    in_scope_note="[CONFIRM: each line above against Highlights' standard scope]",
    separate_heading="Quoted separately, when needed",
    separate="The water heater or pump itself || Plumbing and venting || Panel or service upgrade || Well pump controls below ground",
    handover_heading="What you should have at handover",
    handover="Labelled breaker in the panel || Disconnect at the unit || Permit closed where one was needed || Written workmanship warranty",
    warranty_heading="Who warrants what",
    cta_heading="Need a water heater circuit", cta_body="Free estimate, a written scope before we start, and a contractor registered to pull the permit if the work needs one.",
    ready_heading="Have these ready when you call",
    ready_items="A photo of the unit's label (voltage and watts or amps) || A photo of your electrical panel, door open || Distance from the panel to the unit, roughly || Your plumber's schedule, if one is involved",
    guide_title="Water Heater & Well Pump Wiring — Detail", guide_heading="Water heater and pump circuits: the practical detail",
    guide_intro="Electric water heaters and pumps are some of the largest single loads in a home. They need their own circuit, sized to the unit, with a way to switch them off safely.",
)
items(S, "form_field", ["symptom", "If something stopped working, what is it doing?", "Not applicable || No hot water || Breaker keeps tripping || Pump not running || Low or no water pressure || Burning smell or scorch marks"])
items(S, "job_path",
      ["New electric water heater circuit", "You are installing or replacing an electric tank water heater.", "The unit's rating, the distance to the panel, and panel space.", "Send a photo of the unit's label.", "What we check", "site-assessment"],
      ["Switching from gas to electric", "You are replacing a gas water heater with an electric or heat pump model.", "Whether your panel and service can carry a new large load.", "Panel and service check.", "If the panel is short", "assessment-routes"],
      ["Tankless electric water heater", "You want on-demand electric hot water.", "Tankless units draw a very large current and often need service capacity.", "Panel and service check.", "Tank or tankless", "equipment-choices"],
      ["Well pump wiring or repair", "Your property has a well pump that needs a new circuit or has stopped.", "Pump type, controls, and distance to the panel.", "Diagnostic visit.", "Symptoms and checks", "diagnose"])
items(S, "equipment",
      ["Tank water heater circuits", "Dedicated 240V supply"], ["Tankless water heater circuits", "High-amperage supply"],
      ["Heat pump water heaters", "Circuit to the maker's spec"], ["Well pump circuits", "240V supply and controls"],
      ["Disconnects", "A safe shutoff at the unit"], ["Timers & controls", "Scheduling and pump controls"])
items(S, "compare_row",
      ["Circuit needed", "One dedicated 240V circuit", "Often more than one large circuit", "One dedicated circuit, often smaller"],
      ["Effect on your panel", "Moderate", "Large; may need a service upgrade", "Moderate"],
      ["Best fit", "Most replacements", "Homes with service capacity to spare", "Efficiency-focused replacements"],
      ["Check before buying", "Unit rating and existing wire", "Your service size", "Unit rating and space"])
items(S, "assess_check",
      ["The unit's electrical rating", "Voltage and watts or amps decide the breaker and wire size."],
      ["Existing wire and breaker", "Replacing a unit with a larger one on old wire is a common cause of overheating."],
      ["Panel space", "A 240V circuit needs two spaces in the panel."],
      ["Service size", "Tankless and gas-to-electric switches can exceed what a 100A service can carry."],
      ["Distance and route", "From the panel to the unit, through floors and walls."],
      ["Disconnect", "A shutoff the code requires at or within sight of the unit."],
      ["Pump controls", "For wells: the pressure switch and control box and their condition."])
items(S, "route",
      ["The panel has room", "A new dedicated circuit from the existing panel."],
      ["The panel is full, the service is fine", "Rearranging circuits or a larger panel to make space."],
      ["The service is too small", "A service upgrade first, often 100A to 200A, then the circuit. ComEd schedules its part."])
items(S, "symptom",
      ["No hot water", "Tripped breaker, failed element or thermostat, loose connection", "Breaker, voltage at the unit, then elements"],
      ["Breaker keeps tripping", "Failed element, undersized breaker, damaged wire", "Wire and breaker sizing, then the unit"],
      ["Pump not running", "Tripped breaker, failed pressure switch, failed control box or pump", "Voltage at the pressure switch and control box"],
      ["Low or no water pressure", "Pump cycling on a faulty pressure switch, a failing pump", "Pressure switch and pump current"],
      ["Burning smell or scorch marks", "Overheated connection or undersized wire", "Switch it off and call; we check terminations first"])
items(S, "why",
      ["We schedule around your plumber", "The circuit has to be ready when the unit goes in. Sequencing is the value.", "", ""],
      ["Dedicated circuit, sized properly", "We size wire and breaker to the unit's label, not to whatever was there before.", "What we check", "site-assessment"],
      ["We check the panel first", "Gas-to-electric switches and tankless units can exceed a 100A service. Better to know before you buy.", "If the panel is short", "assessment-routes"],
      ["Permit pulled and closed in-house", "ECC96456 and ECC94521. Outlets and circuits are among our most frequent permitted work.", "", ""],
      ["We take the small job", "Our public permit record contains 54 projects under $5,000, and outlets and circuits are our highest-frequency work.", "", ""],
      ["Salaried crews, scope pricing", "Written scope, no commission.", "", ""])
items(S, "process_step",
      ["Check", "We confirm the unit's rating, the panel and the route. [CONFIRM: typical visit length]", "highlights"],
      ["Written scope", "Circuit, disconnect, any panel work and the price, in writing.", "highlights"],
      ["Permit, where required", "We apply; the City reviews and issues.", "city"],
      ["Circuit installed", "Wire, breaker and disconnect, ready for the unit.", "highlights"],
      ["Unit installed", "Your plumber installs the water heater or pump.", "customer"],
      ["Connection and test", "We connect, test under load and label the breaker.", "highlights"],
      ["Inspection", "Where a permit was pulled, the inspector checks the work.", "city"])
items(S, "other_service",
      ["Garbage Disposal Wiring", "Dedicated circuits under the sink, done to inspection standard.", LIVE + "garbage-disposal-wiring"],
      ["Electrical Panel Upgrade", "When the panel can't take another large load.", LIVE + "electrical-panel-upgrade"],
      ["Energy Star Appliances", "Circuits for efficient appliances.", LIVE + "energy-star-appliances"],
      ["Electrical Outlet Installation", "New outlets and circuits across Chicago homes.", LIVE + "electrical-outlet-installation"])
items(S, "price_row",
      ["100A service (2,190 permits)", "$3,000 median reported", "Yes"],
      ["200A service upgrade (2,863 permits)", "$4,700 median reported", "Yes"],
      ["New water heater circuit", "Distance to the panel and panel space", "Usually"],
      ["Reconnecting a replacement water heater", "Whether the existing wire suits the new unit", "Sometimes"],
      ["Tankless water heater circuit", "Unit size and service capacity", "Yes"],
      ["Well pump circuit or repair", "Pump type, controls and distance", "Sometimes"])
items(S, "cost_driver",
      ["Unit size", "Larger units need heavier wire and bigger breakers", "From the unit's label"],
      ["Distance to the panel", "Longer runs mean more wire and labour", "Check visit"],
      ["Panel space", "A full panel needs rearranging or replacing", "Check visit"],
      ["Service size", "A small service may need upgrading first", "Check visit"],
      ["Existing wire", "Old wire may be too small for a new unit", "Check visit"],
      ["Coordination", "Return visits if the unit arrives late", "During the job"])
items(S, "warranty",
      ["Workmanship", "Highlights Chicago. [CONFIRM: term and what it covers]"],
      ["Water heater or pump", "The manufacturer, through your plumber or supplier."])
items(S, "faq",
      ["Does an electric water heater need a dedicated circuit?", "Yes. It is one of the largest loads in a home and needs its own 240V circuit sized to the unit."],
      ["Can I swap my gas water heater for an electric one?", "Often, but check the panel first. A new large load can exceed what a 100A service carries."],
      ["Do tankless electric water heaters need a bigger service?", "Frequently. They draw a very large current while running. We check your service before you buy."],
      ["Do you install the water heater itself?", "Our scope is the electrical work. We coordinate with your plumber for the unit."],
      ["Do you wire well pumps in Chicago?", "Most Chicago homes are on city water. [CONFIRM: where Highlights takes well pump work]"],
      ["Is a permit needed?", "A new circuit generally needs one. Reconnecting a like-for-like replacement often does not."])
items(S, "guide_section",
      ["Why the circuit has to match the unit", "A water heater's label gives its voltage and power. The wire and breaker are sized from that. Fitting a larger unit on the old circuit is a common cause of overheated connections."],
      ["Gas to electric in older Chicago homes", "Many homes still run on 100A services. An electric water heater, plus everything else added over the years, can push the service past its limit. The panel check comes before the purchase."],
      ["Tankless units", "Tankless electric water heaters heat water only when it flows, but draw a very large current while they do. Many need more than one circuit and a service with room to spare."],
      ["Well pumps", "A well pump runs on a dedicated 240V circuit, switched by a pressure switch and, for some pumps, a control box. When the pump stops, the fault is often in those controls rather than the pump itself."])

# ---------------------------------------------------------------------------
# 344 Dimmer switch installation & replacement
# ---------------------------------------------------------------------------
S = "344"
page(
    service_id=S, slug="dimmer-switch-installation-and-replacement", name="Dimmer Switch Installation & Replacement",
    parent_name="Outlets, Switches & Controls", area_slug="chicago",
    meta_title="Dimmer Switch Installation & Replacement in Chicago",
    meta_description="A dimmer has to match the bulbs it controls. We fix flicker, buzz and dead dimmers and install smart dimmers on Chicago wiring. Call (773) 262-3333.",
    kw_primary="dimmer switch installation || dimmer switch replacement", kw_volume="420",
    kw_secondary="",
    h1_prefix="Dimmer Switch Installation and Replacement",
    hero_lede="Most dimmer problems are a mismatch, not a fault: LED bulbs on a dimmer built for incandescent, a smart dimmer with no neutral wire, or too many dimmers crowded in one box. We match the dimmer to the lights and the wiring behind it.",
    cta_secondary="Book a Dimmer Install",
    issue_question="What do you need?",
    issue_options="New dimmer where there's a switch || Replace a dimmer that stopped working || Lights flicker or buzz on a dimmer || Smart dimmer installation || Several rooms or a whole home || Not sure which",
    jobs_heading="Which dimmer job is yours?",
    jobs_lede="Dimmer work is four different jobs. Find yours first.",
    jobs_note="Not sure which one fits? Choose “Not sure which” and tell us what bulbs or fixtures the dimmer controls.",
    equip_heading="Dimmers & Controls We Install",
    equip_lede="From single-room dimmers to smart dimming across a whole home.",
    equip_footnote="Flicker and buzz are usually a compatibility problem, not a broken dimmer.",
    equip_footnote_link_label="Symptoms and what we check", equip_footnote_link_anchor="diagnose",
    compare_heading="Standard, LED-rated or smart dimmer: what changes?",
    compare_intro="The right dimmer depends on the bulbs and the wiring in the box.",
    compare_columns="Standard dimmer || LED-rated dimmer || Smart dimmer",
    diagnose_heading="Lights flicker or buzz? What we check",
    diagnose_lede="The symptom tells us where to look. Often the dimmer and the bulbs simply don't match.",
    diagnose_columns="What you're seeing || Common causes we check || Where we start",
    brands_heading="Dimmer & Lighting Control Brands We Install",
    brands_lede="We install the dimmers and controls Chicago homes use most.",
    brands="Lutron || Leviton || Legrand || Pass & Seymour || Hubbell || Eaton || GE || Kasa || Philips || Juno",
    why_heading="Why Highlights Chicago for Dimmers?",
    why_lede="A small job, done with the wiring behind it in mind.",
    areas_callout="For dimmers specifically: older Chicago wiring often has no neutral in the switch box, which rules out some smart dimmers, and metal boxes in plaster walls are often too shallow for larger dimmers.",
    feature_tag="Main category", feature_title="All Outlets, Switches & Controls Services",
    feature_desc="Every service we offer in the Outlets, Switches & Controls cluster across Chicago.",
    pricing_heading="What Dimmer Work Costs",
    pricing_lede="Dimmer work is not its own permit category. The closest reported median is for lighting work, which covers whole projects.",
    pricing_caption=CAPTION, pricing_columns=PRICE_COLS,
    pricing_note=PERMIT_NOTE + " A single dimmer swap costs far less than the lighting median.",
    drivers_heading="What moves the price of dimmer work",
    cta_heading="Want dimmers that work", cta_body="Free estimate and a written scope before we start.",
    ready_heading="Have these ready when you call",
    ready_items="How many dimmers, and in which rooms || What bulbs or fixtures each one controls || A photo of the existing switch and, if safe, the wires behind it || Which smart home app you use, if any",
    guide_title="Dimmer Switch Installation — Detail", guide_heading="Dimmers and LED lighting: the practical detail",
    guide_intro="Dimmers were designed for incandescent bulbs. LED lighting changed the rules, which is why so many dimmers flicker, buzz or stop at half brightness.",
)
items(S, "form_field", ["symptom", "If there's a problem, what is it doing?", "Not applicable || Lights flicker || Dimmer buzzes or hums || Lights won't dim fully || Dimmer feels hot || Dimmer stopped working"])
items(S, "job_path",
      ["New dimmer", "You have a regular switch and want to dim the lights.", "The bulbs or fixtures it controls, and the box size.", "Tell us the bulbs.", "Which dimmer", "equipment-choices"],
      ["Replace a dimmer", "A dimmer stopped working or feels hot.", "Why it failed, and whether the replacement matches the load.", "Diagnostic visit.", "Symptoms and checks", "diagnose"],
      ["Fix flicker or buzz", "The lights flicker, buzz or won't dim properly.", "Dimmer and bulb compatibility, and the minimum load.", "Tell us the dimmer and bulb models.", "Symptoms and checks", "diagnose"],
      ["Smart dimmers", "You want app or voice control, or dimmers across several rooms.", "Whether there is a neutral wire, and your smart home system.", "A photo of the wires in the box.", "Which dimmer", "equipment-choices"])
items(S, "equipment",
      ["Single-pole dimmers", "One dimmer, one light group"], ["Three-way dimmers", "Dim from two locations"],
      ["LED-rated dimmers", "Matched to LED loads"], ["Smart dimmers", "App and voice control"],
      ["Fan & light controls", "Separate speed and dimming"], ["Multi-gang dimmers", "Several dimmers in one box"])
items(S, "compare_row",
      ["Best for", "Incandescent and halogen bulbs", "Dimmable LED bulbs and fixtures", "LEDs, with app or voice control"],
      ["Flicker risk with LEDs", "High", "Low when matched", "Low when matched"],
      ["Needs a neutral wire", "No", "Usually no", "Often yes"],
      ["Works from two locations", "With a three-way model", "With a three-way model", "Usually with a companion switch"])
items(S, "symptom",
      ["Lights flicker when dimmed", "Dimmer not rated for LEDs, mixed bulb types, load below the dimmer's minimum", "Dimmer and bulb models"],
      ["Dimmer buzzes or hums", "Incompatible dimmer and bulbs, a loose connection", "Compatibility, then terminations"],
      ["Lights won't dim fully or turn off", "Dimmer range not set, minimum load not met", "Dimmer settings and total load"],
      ["Dimmer feels hot", "Normal warmth versus overload or crowded box", "Total load against the rating"],
      ["Dimmer stopped working", "Failed dimmer, loose connection, tripped breaker", "Voltage at the box, then the device"])
items(S, "why",
      ["We match the dimmer to the load", "Not every dimmer works with every LED. We check the bulbs first.", "Which dimmer", "equipment-choices"],
      ["We take the single-dimmer job", "Small switch and dimmer jobs are routine for us.", "", ""],
      ["Older wiring, handled honestly", "If your box has no neutral, we tell you before installing a smart dimmer that needs one.", "", ""],
      ["Flicker diagnosed, not guessed", "We find whether it's the dimmer, the bulbs or the wiring.", "Symptoms and checks", "diagnose"],
      ["Registered electrical contractor", "ECC96456 and ECC94521.", "", ""],
      ["Salaried crews, scope pricing", "A small job priced as a small job.", "", ""])
items(S, "other_service",
      ["Light Switch Replacement & Installation", "Switches that spark, feel loose or don't work.", LIVE + "light-switch-replacement-and-installation"],
      ["Recessed Lighting Installation", "Ten to seventeen fixtures is a normal Chicago condo scope.", LIVE + "recessed-lighting-installation"],
      ["Light Fixture Installation & Replacement", "Fixtures hung on boxes rated for them.", LIVE + "light-fixture-installation-and-replacement"],
      ["Ceiling Fan Installation", "Fans on boxes rated to carry them.", LIVE + "ceiling-fan-installation"])
items(S, "price_row",
      ["Lighting (9,748 permits)", "$4,000 median reported, whole projects", "Where permitted"],
      ["Dimmer replacing a switch", "Box size and load type", "Usually not"],
      ["Smart dimmer", "Whether a neutral wire is present", "Usually not"],
      ["Three-way dimmer", "Number of switch locations and wiring", "Usually not"],
      ["Flicker diagnosis", "Time to test bulbs and dimmer", "No"])
items(S, "cost_driver",
      ["Number of dimmers", "Several on one visit costs less per dimmer", "When you call"],
      ["Dimmer type", "Smart and LED-rated dimmers cost more than standard ones", "When you choose"],
      ["Neutral wire", "No neutral can mean a different dimmer or new wiring", "On site"],
      ["Box size", "Shallow or crowded boxes may need replacing", "On site"],
      ["Bulbs", "Incompatible bulbs may need replacing to stop flicker", "On site"])
items(S, "faq",
      ["Why do my LED lights flicker on a dimmer?", "Usually the dimmer is not rated for LEDs, the bulbs are not dimmable, or the load is below the dimmer's minimum. Matching them fixes it."],
      ["Can any light be put on a dimmer?", "Only dimmable bulbs and fixtures. Non-dimmable LEDs can flicker or fail on a dimmer."],
      ["Do smart dimmers need a neutral wire?", "Many do. Older Chicago wiring often lacks one in the switch box, so we check before you buy."],
      ["Is it normal for a dimmer to feel warm?", "Slightly warm, yes. Hot to the touch, or warm with a smell, is not; switch it off and have it checked."],
      ["Can I dim from two locations?", "Yes, with three-way dimmers or a smart dimmer and companion switch."],
      ["Is a permit needed to install a dimmer?", "Generally not for replacing a switch with a dimmer. New circuits are different."])
items(S, "guide_section",
      ["Why LEDs and old dimmers don't mix", "Older dimmers were designed for the steady load of incandescent bulbs. LED bulbs draw far less power and use electronics that react differently, which shows up as flicker, buzz or a limited dimming range."],
      ["Minimum load", "Many dimmers need a minimum total load to work smoothly. A few low-wattage LEDs may fall below it. The fix is a dimmer with a lower minimum, or adjusting its range."],
      ["Several dimmers in one box", "When dimmers share a box, their ratings usually drop because heat has less room to escape. We check the total load against the derated rating."],
      ["Smart dimmers in older homes", "Many smart dimmers need a neutral wire in the switch box. In older Chicago homes it is often missing. Some models work without one; otherwise new wiring is needed."])

# ---------------------------------------------------------------------------
# 345 Exit sign & egress lighting
# ---------------------------------------------------------------------------
S = "345"
page(
    service_id=S, slug="egress-lighting-requirements", name="Exit Sign & Egress Lighting Installation",
    parent_name="Exterior, Egress & Commercial Lighting", area_slug="chicago",
    meta_title="Exit Sign & Egress Lighting Installation in Chicago",
    meta_description="Exit signs and emergency lights have to work on battery when the power fails. We install, test and correct them for Chicago buildings. Call (773) 262-3333.",
    kw_primary="egress lighting requirements || exit sign installation", kw_volume="410",
    kw_secondary="exit sign maintenance || exit sign testing",
    h1_prefix="Exit Sign and Egress Lighting Installation",
    hero_lede="Exit signs and egress lights have one job: when normal power fails, light the way out. We install, test and correct them for Chicago commercial and multi-unit buildings, so they pass inspection and work when it counts.",
    cta_secondary="Book an Egress Review",
    issue_question="What do you need?",
    issue_options="New exit signs or emergency lights || Units failing their test || Inspection violation to correct || Routine testing and maintenance || Renovation or change of use || Not sure which",
    jobs_heading="Which egress job is yours?",
    jobs_lede="Egress lighting work comes in four shapes. Find yours first.",
    jobs_note="Not sure which one fits? Choose “Not sure which” and send the inspection notice if you have one.",
    equip_heading="Exit & Egress Lighting We Install and Service",
    equip_lede="Exit signs, battery-backed emergency lights and the circuits that feed them.",
    compare_heading="Battery units, remote heads or central power: what changes?",
    compare_intro="How emergency power is supplied decides the maintenance load.",
    compare_columns="Self-contained battery units || Remote-head systems || Central power (inverter or generator)",
    assess_heading="What the egress review checks",
    assess_lede="Requirements follow the path people take out of the building, not single fixtures.",
    diagnose_heading="Units failing their test? What we check",
    diagnose_lede="A failed test button can mean a battery, lamp, charger or supply problem.",
    diagnose_columns="What you're seeing || Common causes we check || Where we start",
    repair_title="Repair or replace?",
    repair_body="If the fixture and charger are sound and parts are available, we replace the battery or lamp. Older units with failed electronics, or units that no longer meet current requirements, are usually replaced.",
    orphan_title="Have an inspection notice?",
    orphan_body="Send it with the call. We scope the corrections against the notice so the re-inspection goes to the items cited.",
    brands_heading="Exit & Emergency Lighting Brands We Install",
    brands_lede="We install and service the brands most Chicago buildings already have.",
    brands="Lithonia || Cooper Lighting || Hubbell || Philips || RAB Lighting || Eaton || Legrand || Leviton || Square D || Siemens",
    why_heading="Why Highlights Chicago for Egress Lighting?",
    why_lede="Egress lighting is life-safety work, and inspections are specific.",
    process_heading="From review to passed inspection",
    process_lede="Some steps are ours, some are the City's.",
    areas_callout="For egress lighting specifically: older Chicago courtyard and walk-up buildings often have long corridors and stairs with few circuits, and mixed-use buildings may have different requirements for the commercial and residential parts. [CONFIRM: Chicago-specific exit sign requirements, such as sign colour, before stating them]",
    feature_tag="Main category", feature_title="All Exterior, Egress & Commercial Lighting Services",
    feature_desc="Every service we offer in the Exterior, Egress & Commercial Lighting cluster across Chicago.",
    pricing_heading="What Exit & Egress Lighting Costs",
    pricing_lede="Egress lighting is reported inside Chicago's lighting permits. The scope drivers below decide most of the price.",
    pricing_caption=CAPTION, pricing_columns=PRICE_COLS, pricing_note=PERMIT_NOTE,
    drivers_heading="What moves the price of egress lighting",
    incl_heading="What's included, what isn't, and what you get at the end",
    incl_lede="For life-safety work, the record at the end matters as much as the work.",
    in_scope_heading="In a typical egress scope",
    in_scope="Walk of the egress path || Units installed or replaced || Battery and lamp replacement where serviceable || Functional test of every unit || Permit and inspection where required",
    in_scope_note="[CONFIRM: each line above against Highlights' standard scope]",
    separate_heading="Quoted separately, when needed",
    separate="New circuits from the panel || Ceiling repairs || Fire alarm work || Lift equipment for high ceilings",
    handover_heading="What you should have at handover",
    handover="A list of every unit and its location || Test results for each unit || Corrections made against any inspection notice || Permit closed where one was needed",
    warranty_heading="Who warrants what",
    cta_heading="Need exit signs that pass", cta_body="Free estimate, a written scope before we start, and a contractor registered to pull the permit if the work needs one.",
    ready_heading="Have these ready when you call",
    ready_items="Any inspection notice or violation || A floor plan or photos of corridors and stairs || The number of units, if known || Building type and use || Who can give access on the day",
    guide_title="Exit Sign & Egress Lighting — Detail", guide_heading="Egress lighting requirements: the practical detail",
    guide_intro="Egress lighting is about the path out of a building: corridors, stairs and exits. When normal power fails, it has to light that path on its own.",
)
items(S, "job_path",
      ["New exit signs or emergency lights", "You are fitting out a space, or units are missing.", "The egress path, ceiling heights and available circuits.", "Egress review.", "What the review checks", "site-assessment"],
      ["Units failing their test", "The test button does nothing, or the light dies quickly.", "Whether it is the battery, lamp, charger or supply.", "Diagnostic visit.", "Symptoms and checks", "diagnose"],
      ["Inspection correction", "You have a notice citing exit signs or emergency lighting.", "The items cited and the building's use.", "Send the notice.", "What happens next", "process"],
      ["Routine testing", "You want units tested and recorded on a schedule.", "Number of units, floors and access.", "Unit count and floor plan.", "Battery or central power", "equipment-choices"])
items(S, "equipment",
      ["Exit signs", "LED, battery-backed"], ["Emergency light units", "Battery-backed path lighting"],
      ["Combination units", "Exit sign and lights together"], ["Remote heads", "Lights fed from one battery unit"],
      ["Exterior egress lights", "Lighting outside the exit door"], ["Unswitched supply circuits", "Power that can't be switched off"])
items(S, "compare_row",
      ["Where the battery is", "In every unit", "In one unit feeding several heads", "One central source"],
      ["Maintenance", "Test and replace batteries unit by unit", "Fewer batteries to maintain", "Central equipment maintained by specialists"],
      ["Best fit", "Most small and mid-size buildings", "Long corridors and stairs", "Large buildings"],
      ["Cost to add units", "Low", "Moderate", "Higher"])
items(S, "assess_check",
      ["The egress path", "Every corridor, stair and exit people use to leave."],
      ["Exit sign placement", "Signs must be visible along the path and at each exit."],
      ["Light levels", "The path must be lit well enough to see, including on battery."],
      ["Battery duration", "Units must run for the required time on battery."],
      ["Unswitched supply", "Units need a supply that a light switch can't turn off."],
      ["Unit condition and age", "Old units may not hold a charge or meet current rules."],
      ["Building use", "Requirements differ by occupancy. [CONFIRM: which occupancies Highlights handles]"])
items(S, "symptom",
      ["Test button does nothing", "Failed battery, failed charger, lost supply", "Supply first, then battery and charger"],
      ["Light dies before the test ends", "Battery at end of life", "Battery age and charge"],
      ["Exit sign is dark", "Failed LED module, lost supply, failed battery", "Supply, then the module"],
      ["Charging light off", "No supply or a failed charger", "Supply at the unit"],
      ["Unit beeps or shows a fault", "Self-test failure", "The fault code and the battery"])
items(S, "why",
      ["Testing before replacement", "A failed test can be a battery, lamp, charger or supply problem.", "Symptoms and checks", "diagnose"],
      ["The egress path, not single fixtures", "We review the whole route out, which is what inspectors look at.", "What the review checks", "site-assessment"],
      ["A record you can show", "Every unit listed, tested and corrected.", "", ""],
      ["Permit and inspection handled", "ECC96456 and ECC94521. Our record shows 527 permits through the Express Permit Program.", "", ""],
      ["Commercial access planned", "Lifts, occupied spaces and after-hours work built into the scope.", "", ""],
      ["Salaried crews, scope pricing", "Written scope against the actual building.", "", ""])
items(S, "process_step",
      ["Egress review", "We walk the path and list every unit and gap. [CONFIRM: typical review length]", "highlights"],
      ["Written scope", "Units, repairs, circuits and price, in writing.", "highlights"],
      ["Permit, where required", "We apply; the City reviews and issues.", "city"],
      ["Installation and repairs", "Units installed, batteries replaced, supplies corrected.", "highlights"],
      ["Testing", "Every unit tested on battery and recorded.", "highlights"],
      ["Inspection", "Where required, the inspector checks the work; we attend.", "city"])
items(S, "other_service",
      ["Fire Alarm Installation", "Detection and notification that works with your egress plan.", LIVE + "fire-alarm-installation"],
      ["Outdoor Lighting Installation", "Weather-rated exterior lighting and controls.", LIVE + "outdoor-lighting-installation"],
      ["Smoke Detector Installation & Wiring", "Hardwired, interconnected detection.", LIVE + "smoke-detector-installation-and-wiring"],
      ["Electrical Troubleshooting", "Circuit and control faults traced systematically.", LIVE + "electrical-troubleshooting"])
items(S, "price_row",
      ["Lighting (9,748 permits)", "$4,000 median reported, whole projects", "Where permitted"],
      ["Battery or lamp replacement", "Battery type and number of units", "No"],
      ["New exit sign or emergency unit", "Mounting, supply and ceiling access", "Often"],
      ["Inspection correction package", "Number of items cited", "Often"],
      ["Testing and record", "Unit count, floors and access", "No"])
items(S, "cost_driver",
      ["Number of units", "Each unit is a test, and often a battery", "Review"],
      ["Supply circuits", "Missing unswitched supplies mean new wiring", "Review"],
      ["Ceiling height and access", "High ceilings need lifts", "Review"],
      ["Unit age", "Old units are often cheaper to replace than repair", "Testing"],
      ["After-hours work", "Occupied buildings may need work outside hours", "Written scope"],
      ["Inspection items", "The notice decides the minimum scope", "When you send it"])
items(S, "warranty",
      ["Workmanship", "Highlights Chicago. [CONFIRM: term and what it covers]"],
      ["Units and batteries", "The manufacturer. Terms vary by brand."])
items(S, "faq",
      ["How long must emergency lights run on battery?", "The common standard is 90 minutes. [CONFIRM: the requirement the City applies to each building type]"],
      ["How often should exit signs be tested?", "The common standard (NFPA 101) calls for a short functional test monthly and a full-duration test yearly. [CONFIRM: the schedule Chicago enforces]"],
      ["Why does my emergency light fail the test?", "Usually a worn-out battery, a failed charger or a lost supply. Testing tells us which."],
      ["Can you replace just the battery?", "Yes, when the unit and charger are sound and the right battery is available."],
      ["Do new exit signs need a permit?", "New wiring and circuit changes commonly do. We confirm the permit path from the final scope."],
      ["Can you give us a testing record?", "Yes. Every unit, its location, the result and any work done."])
items(S, "guide_section",
      ["What egress lighting is for", "When normal power fails, people still need to find the way out. Exit signs mark the route; emergency lights make it visible. Both have to work on their own power."],
      ["Battery duration and testing", "Battery-backed units are commonly required to run for 90 minutes. Batteries wear out, which is why regular testing matters more than the fixture itself."],
      ["Older Chicago buildings", "Walk-up and courtyard buildings often have long corridors and stairs fed by few circuits. Adding units sometimes means adding an unswitched supply, which is the part that takes time."],
      ["Inspection notices", "A notice lists specific items. Correcting exactly those, and recording the tests, is the fastest route to a passed re-inspection."])
